language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frankypassword123/react-app -f ./client/Dev.Dockerfile ./client

script:
  - docker run -e CI=true frankypassword123/react-app npm test

after_success:
  - docker build -t frankypassword123/multi-client ./client
  - docker build -t frankypassword123/multi-nginx ./nginx
  - docker build -t frankypassword123/multi-server ./server
  - docker build -t frankypassword123/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to docker hub
  - docker push frankypassword123/multi-client
  - docker push frankypassword123/multi-nginx
  - docker push frankypassword123/multi-server
  - docker push frankypassword123/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-ap-southeast-2-073032805649
  bucket_path: new-docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
